name: RandomTeleport
version: 1.5
main: me.blitzgamer_88.randomteleport.RandomTeleport
api-version: 1.13
softdepend: [PlaceholderAPI, WorldGuard, Lands]
author: BlitzGamer_88
website: github.com/blitzgamer-88